### ISSUE TITLE
Mex_Compiler Error

### ISSUE THREAD

**Issue by mgerber000** [suever/regionalDyssynchrony#1]
I've been getting this error message while trying to use the mex_complier. The rest of the package doesn't work if I can't compile the mex. I have never seen this error and I have no experience with c-files so my troubleshooting is limited.

> > compile_mex
> > Building with 'MinGW64 Compiler (C)'.
> > Error using mex
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:
> > In function 'mexFunction':
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:53:5:
> > error: unknown type name 'int32_t'
> >      int32_t _lags, lag;
> >      ^
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:130:16:
> > error: 'int32_t' undeclared (first use in this function)
> >      lags    = (int32_t_)mxGetPr(plhs[1]);
> >                 ^
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:130:16:
> > note: each undeclared identifier is reported only once for each function it appears in
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:130:24:
> > error: expected expression before ')' token
> >      lags    = (int32_t*)mxGetPr(plhs[1]);
> >                         ^

Error in compile_mex (line 10)
    mex('-largeArrayDims', ...

**Comment by suever** [comment]
Can you try adding the following line after line 13 of xcorrPeriodic.c?

```
typedef int int32_t;
```

**Comment by suever** [comment]
Alternately, you could try replacing `int32_t` with `INT32_T`

**Comment by mgerber000** [comment]
I've tried both capital and lowercase and the error is the same

> > compile_mex
> > Building with 'MinGW64 Compiler (C)'.
> > Error using mex
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:
> > In function 'mexFunction':
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:53:5:
> > error: unknown type name 'int32_t'
> >      int32_t _lags, lag;
> >      ^
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:130:16:
> > error: 'int32_t' undeclared (first use in this function)
> >      lags    = (int32_t_)mxGetPr(plhs[1]);
> >                 ^
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:130:16:
> > note: each undeclared identifier is reported only once for each function it appears in
> > C:\Users\michael\Desktop\regionalDyssynchrony-master\regionalDyssynchrony-master\mex\xcorrPeriodic.c:130:24:
> > error: expected expression before ')' token
> >      lags    = (int32_t*)mxGetPr(plhs[1]);
> >                         ^

Error in compile_mex (line 10)
    mex('-largeArrayDims', ...

I've switched over to OSX in the meanwhile to see if I can get it to work with Xcode7

**Comment by suever** [comment]
Where did you make the changes from `int32_t` to `INT32_T`? I failed to specify that the change in capitalization should be done to every occurrence of `int32_t` in the original source code, not the code that was changed by my first suggestion.

**Comment by mgerber000** [comment]
I only capitalized in the MATLAB code. If that's what you mean I'll have to download the software to read the c-files. I'm assuming that's what you mean by source code.

**Comment by mgerber000** [comment]
Replacing "int32_t to INT32_T in the source code worked. Thank you very much for your help!

**Comment by suever** [comment]
Great! I'll push the changes. Thanks for pointing this out.

**Comment by suever** [comment]
Closed by 8f1c287b58052745b87aeda3b229a559e963ce4d
